services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - DEEPINFRA_API_TOKEN=${DEEPINFRA_API_TOKEN}
      - DEBUG=${DEBUG:-False}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MILVUS_URI=${MILVUS_URI}
      - MILVUS_TOKEN=${MILVUS_TOKEN}
      - MILVUS_COLLECTION=${MILVUS_COLLECTION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
